// Player data for men's and women's brackets

const menPlayersData = [
    // Left side of bracket (32 players)
    { name: 'Y.KUROKAWA', nameJp: '黒川 雄大', prefecture: 'Kanagawa', rank: 5, age: 24 },
    { name: 'T.CHIKAMOTO', nameJp: '近本 太郎', prefecture: 'Aichi', rank: 5, age: null },
    { name: 'Y.YAMADA', nameJp: '山田 侑希', prefecture: 'Nara', rank: 'R6', age: null },
    { name: 'Y.OKUMURA', nameJp: '奥村 優太', prefecture: 'Hokkaido', rank: 5, age: null },
    { name: 'H.SOMEYA', nameJp: '', prefecture: 'Chiba', rank: 5, age: null },
    { name: 'M.HATSUKANO', nameJp: '', prefecture: 'Tottori', rank: 4, age: null },
    { name: 'K.SHIMOKUBO', nameJp: '', prefecture: 'Miyazaki', rank: 'R6', age: null },
    { name: 'T.MORIMOTO', nameJp: '', prefecture: 'Kagawa', rank: 'R6', age: null },
    { name: 'K.SENDA', nameJp: '', prefecture: 'Miyagi', rank: 5, age: null },
    { name: 'R.KUNITOMO', nameJp: '', prefecture: 'Fukuoka', rank: 'R6', age: null },
    { name: 'Y.NAKANE', nameJp: '', prefecture: 'Ibaraki', rank: 5, age: null },
    { name: 'S.NISHIZAWA', nameJp: '', prefecture: 'Nagano', rank: 5, age: null },
    { name: 'Y.TAKENOUCHI', nameJp: '', prefecture: 'Tokyo', rank: 6, age: null },
    { name: 'S.MAEDA', nameJp: '', prefecture: 'Hyogo', rank: 6, age: null },
    { name: 'Y.MATSUOKA', nameJp: '', prefecture: 'Mie', rank: 5, age: null },
    { name: 'R.KAMOI', nameJp: '', prefecture: 'Okayama', rank: 5, age: null },
    { name: 'T.UEZU', nameJp: '', prefecture: 'Okinawa', rank: 'R7', age: null },
    { name: 'K.TAKEMOTO', nameJp: '', prefecture: 'Shiga', rank: 4, age: null },
    { name: 'R.NATSUMEDA', nameJp: '', prefecture: 'Hiroshima', rank: 4, age: null },
    { name: 'H.HOSHINO', nameJp: '', prefecture: 'Gunma', rank: 5, age: null },
    { name: 'T.YAMAZAKI', nameJp: '', prefecture: 'Ishikawa', rank: 5, age: null },
    { name: 'N.TASHIRO', nameJp: '', prefecture: 'Fukuoka', rank: 4, age: null },
    { name: 'Y.ITO', nameJp: '', prefecture: 'Saitama', rank: 4, age: null },
    { name: 'H.ISHIDA', nameJp: '', prefecture: 'Yamagata', rank: 5, age: null },
    { name: 'R.SEIKE', nameJp: '', prefecture: 'Osaka', rank: 5, age: null },
    { name: 'K.MUKUNASHI', nameJp: '', prefecture: 'Tokyo', rank: 5, age: null },
    { name: 'T.TAKADA', nameJp: '', prefecture: 'Aomori', rank: 'R6', age: null },
    { name: 'K.KUSUNOKI', nameJp: '', prefecture: 'Shimane', rank: 4, age: null },
    { name: 'R.SUZUKI', nameJp: '', prefecture: 'Chiba', rank: 4, age: null },
    { name: 'E.KANASAKI', nameJp: '', prefecture: 'Toyama', rank: 4, age: null },
    { name: 'M.KUROKI', nameJp: '', prefecture: 'Oita', rank: 5, age: null },
    { name: 'T.MURAKAMI', nameJp: '', prefecture: 'Ehime', rank: 'R6', age: null },

    // Right side of bracket (32 players)
    { name: 'K.NAKAZAWA', nameJp: '', prefecture: 'Kochi', rank: 'R6', age: null },
    { name: 'S.MATSUI', nameJp: '', prefecture: 'Tochigi', rank: 5, age: null },
    { name: 'K.MATSUZAKI', nameJp: '', prefecture: 'Ibaraki', rank: 5, age: null },
    { name: 'T.NAGANO', nameJp: '', prefecture: 'Hyogo', rank: 'R6', age: null },
    { name: 'S.HAMASAKI', nameJp: '', prefecture: 'Kagoshima', rank: 6, age: null },
    { name: 'K.KUNIYASU', nameJp: '', prefecture: 'Akita', rank: 5, age: null },
    { name: 'K.OKA', nameJp: '', prefecture: 'Saga', rank: 5, age: null },
    { name: 'S.KANO', nameJp: '', prefecture: 'Tokyo', rank: 6, age: null },
    { name: 'K.KIMURA', nameJp: '', prefecture: 'Osaka', rank: 5, age: null },
    { name: 'H.SAKAMOTO', nameJp: '', prefecture: 'Shimane', rank: 'R6', age: null },
    { name: 'K.HASHIMOTO', nameJp: '', prefecture: 'Saitama', rank: 'R7', age: null },
    { name: 'K.HAYASHIDA', nameJp: '', prefecture: 'Nagasaki', rank: 6, age: null },
    { name: 'S.OTANI', nameJp: '', prefecture: 'Fukushima', rank: 'R6', age: null },
    { name: 'H.ABIRU', nameJp: '', prefecture: 'Tokyo', rank: 4, age: null },
    { name: 'Y.KUDAMATSU', nameJp: '', prefecture: 'Aichi', rank: 5, age: null },
    { name: 'M.TABATA', nameJp: '', prefecture: 'Niigata', rank: 3, age: null },
    { name: 'H.NISHIMURA', nameJp: '', prefecture: 'Kumamoto', rank: 'R7', age: null },
    { name: 'Y.YAMAGUCHI', nameJp: '', prefecture: 'Yamanashi', rank: 6, age: null },
    { name: 'Y.NOMURA', nameJp: '', prefecture: 'Kanagawa', rank: 'R7', age: null },
    { name: 'T.YAMURA', nameJp: '', prefecture: 'Yamaguchi', rank: 5, age: null },
    { name: 'K.HOSHIKO', nameJp: '', prefecture: 'Tokyo', rank: 5, age: null },
    { name: 'T.TSURUHAMA', nameJp: '', prefecture: 'Osaka', rank: 5, age: null },
    { name: 'Y.ITO', nameJp: '', prefecture: 'Gifu', rank: 5, age: null },
    { name: 'S.IZAWA', nameJp: '', prefecture: 'Hokkaido', rank: 6, age: null },
    { name: 'Y.SASAKI', nameJp: '', prefecture: 'Chiba', rank: 5, age: null },
    { name: 'R.NISHIDA', nameJp: '', prefecture: 'Tokushima', rank: 6, age: null },
    { name: 'S.OGURA', nameJp: '', prefecture: 'Wakayama', rank: 5, age: null },
    { name: 'M.FURUDATE', nameJp: '', prefecture: 'Iwate', rank: 'R7', age: null },
    { name: 'S.ABEMATSU', nameJp: '', prefecture: 'Saitama', rank: 6, age: null },
    { name: 'S.TOMITA', nameJp: '', prefecture: 'Fukui', rank: 6, age: null },
    { name: 'R.GOYA', nameJp: '', prefecture: 'Kyoto', rank: 'R6', age: null },
    { name: 'R.IKEDA', nameJp: '', prefecture: 'Fukuoka', rank: 4, age: null }
];

const womenPlayersData = [
    { name: 'R.KUSUNOSE', nameJp: '', prefecture: 'Kagawa', rank: 4, age: null },
    { name: 'A.SEKIKAWA', nameJp: '', prefecture: 'Hokkaido', rank: 4, age: null },
    { name: 'A.YAMADA', nameJp: '', prefecture: 'Shizuoka', rank: 4, age: null },
    { name: 'M.KONDO', nameJp: '', prefecture: 'Tokyo', rank: 6, age: null },
    { name: 'K.SHINOHARA', nameJp: '', prefecture: 'Nara', rank: 'R6', age: null },
    { name: 'S.NAKAMURA', nameJp: '', prefecture: 'Ibaraki', rank: 3, age: null },
    { name: 'A.SHOJIMA', nameJp: '', prefecture: 'Saga', rank: 4, age: null },
    { name: 'M.HATSUKANO', nameJp: '', prefecture: 'Tottori', rank: 5, age: null },
    { name: 'H.MIZUKAWA', nameJp: '', prefecture: 'Osaka', rank: 4, age: null },
    { name: 'A.SHITO', nameJp: '', prefecture: 'Saitama', rank: 6, age: null },
    { name: 'M.YOKOYAMA', nameJp: '', prefecture: 'Ishikawa', rank: 3, age: null },
    { name: 'K.HIGASHINO', nameJp: '', prefecture: 'Aichi', rank: 4, age: null },
    { name: 'M.SUENAGA', nameJp: '', prefecture: 'Wakayama', rank: 'R7', age: null },
    { name: 'A.ISHIJIMA', nameJp: '', prefecture: 'Tochigi', rank: 3, age: null },
    { name: 'Y.SATO', nameJp: '', prefecture: 'Akita', rank: 4, age: null },
    { name: 'S.KAKIMOTO', nameJp: '', prefecture: 'Fukuoka', rank: 4, age: null },
    { name: 'M.SATO', nameJp: '', prefecture: 'Tokyo', rank: 5, age: null },
    { name: 'K.KIKUCHI', nameJp: '', prefecture: 'Kagoshima', rank: 3, age: null },
    { name: 'A.WATANABE', nameJp: '', prefecture: 'Ehime', rank: 5, age: null },
    { name: 'M.OKOMA', nameJp: '', prefecture: 'Gunma', rank: 2, age: null },
    { name: 'K.FUJISAKI', nameJp: '', prefecture: 'Osaka', rank: 5, age: null },
    { name: 'K.MORIZONO', nameJp: '', prefecture: 'Gifu', rank: 3, age: null },
    { name: 'M.TAKAHASHI', nameJp: '', prefecture: 'Kanagawa', rank: 'R6', age: null },
    { name: 'M.SAITO', nameJp: '', prefecture: 'Yamagata', rank: 5, age: null },
    { name: 'H.HASHIMOTO', nameJp: '', prefecture: 'Yamaguchi', rank: 3, age: null },
    { name: 'N.TAMAI', nameJp: '', prefecture: 'Chiba', rank: 4, age: null },
    { name: 'A.KIMURA', nameJp: '', prefecture: 'Hyogo', rank: 'R6', age: null },
    { name: 'M.NAKATSUKA', nameJp: '', prefecture: 'Kumamoto', rank: 3, age: null },
    { name: 'M.OGAWA', nameJp: '', prefecture: 'Aichi', rank: 5, age: null },
    { name: 'K.KOMATSU', nameJp: '', prefecture: 'Miyagi', rank: 5, age: null },
    { name: 'H.NAKAMURA', nameJp: '', prefecture: 'Saitama', rank: 4, age: null },
    { name: 'H.UEKI', nameJp: '', prefecture: 'Niigata', rank: 4, age: null },
    { name: 'A.ONIZUKA', nameJp: '', prefecture: 'Chiba', rank: 5, age: null },
    { name: 'N.KIFA', nameJp: '', prefecture: 'Okinawa', rank: 4, age: null },
    { name: 'Y.MIYABE', nameJp: '', prefecture: 'Shiga', rank: 3, age: null },
    { name: 'S.AWAJI', nameJp: '', prefecture: 'Aomori', rank: 4, age: null },
    { name: 'M.SENO', nameJp: '', prefecture: 'Fukuoka', rank: 5, age: null },
    { name: 'A.NISHIO', nameJp: '', prefecture: 'Kochi', rank: 4, age: null },
    { name: 'K.MORIYAMA', nameJp: '', prefecture: 'Shimane', rank: 6, age: null },
    { name: 'N.UESUGI', nameJp: '', prefecture: 'Tokyo', rank: 4, age: null },
    { name: 'A.OZAKI', nameJp: '', prefecture: 'Kyoto', rank: 'R6', age: null },
    { name: 'H.FUKUHARA', nameJp: '', prefecture: 'Toyama', rank: 4, age: null },
    { name: 'H.ISHIDA', nameJp: '', prefecture: 'Okayama', rank: 4, age: null },
    { name: 'H.RYU', nameJp: '', prefecture: 'Tokyo', rank: 4, age: null },
    { name: 'M.OZONO', nameJp: '', prefecture: 'Nagasaki', rank: 5, age: null },
    { name: 'M.TAKENAKA', nameJp: '', prefecture: 'Ibaraki', rank: 5, age: null },
    { name: 'M.MITSUISHI', nameJp: '', prefecture: 'Yamanashi', rank: 6, age: null },
    { name: 'K.KAWAI', nameJp: '', prefecture: 'Shizuoka', rank: 4, age: null },
    { name: 'M.SAKAI', nameJp: '', prefecture: 'Chiba', rank: 5, age: null },
    { name: 'S.OGAWA', nameJp: '', prefecture: 'Hyogo', rank: 4, age: null },
    { name: 'N.ONISHI', nameJp: '', prefecture: 'Fukui', rank: 6, age: null },
    { name: 'M.ANDO', nameJp: '', prefecture: 'Aichi', rank: 4, age: null },
    { name: 'W.IGARASHI', nameJp: '', prefecture: 'Fukushima', rank: 3, age: null },
    { name: 'R.OGAWA', nameJp: '', prefecture: 'Saitama', rank: 5, age: null },
    { name: 'M.YOKOZAWA', nameJp: '', prefecture: 'Hiroshima', rank: 5, age: null },
    { name: 'R.YAMASAKI', nameJp: '', prefecture: 'Miyazaki', rank: 5, age: null },
    { name: 'Y.OSHIMA', nameJp: '', prefecture: 'Osaka', rank: 4, age: null },
    { name: 'A.NAKA', nameJp: '', prefecture: 'Mie', rank: 3, age: null },
    { name: 'C.MATSUMOTO', nameJp: '', prefecture: 'Kanagawa', rank: 5, age: null },
    { name: 'M.KITAZAWA', nameJp: '', prefecture: 'Nagano', rank: 4, age: null },
    { name: 'C.OMOTE', nameJp: '', prefecture: 'Tokyo', rank: 5, age: null },
    { name: 'K.FUJISAWA', nameJp: '', prefecture: 'Iwate', rank: 'R6', age: null },
    { name: 'C.IWAHARA', nameJp: '', prefecture: 'Tokushima', rank: 4, age: null },
    { name: 'E.KONAKAHARA', nameJp: '', prefecture: 'Oita', rank: 3, age: null }
];
